name: awfar_captain
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  build_runner: ^2.4.8
  flutter_bloc: ^8.1.4
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  dio: ^5.4.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  pretty_dio_logger: ^1.3.1
  intl: ^0.19.0
  easy_localization: ^3.0.5
  flutter_native_splash: ^2.3.11
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  loading_animation_widget: ^1.2.1
  circular_reveal_animation: ^2.0.1
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.1
  flutter_staggered_animations: ^1.1.1
  animated_snack_bar: ^0.4.0
  http_parser: ^4.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.6
  socket_io_client: ^3.0.0-beta.2
  gradient_borders: ^1.0.0
  google_maps_flutter: ^2.2.8
  calendar_date_picker2: ^1.1.5
  location: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800